/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen__closure__destroy__hbb4f3dc832cc9726: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h163d200b6b56d3e4: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hd8739893989ac4d3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h10b73c8a0858c3e6: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6d3421d7889a0c42: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h257fb10f49dc4b74: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dde3d6ad30cb722: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dde3d6ad30cb722_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dde3d6ad30cb722_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dde3d6ad30cb722_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1869ea4d70d90d8f_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h17f7e1964b40556a: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc7cbeace563b12bd: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h53bd13b87e2188ba: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
