/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen__closure__destroy__h4f121b77250bc5d5: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h5a7cd682e23350f8: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h5f03f67cf2f694e3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h03fa493654c43674: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he3dc54c271dd86a6: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h950f328083cecaa0: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13f972db709d9ebc: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13f972db709d9ebc_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13f972db709d9ebc_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13f972db709d9ebc_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bd72c59c282bc74_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha79b72998612a01d: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6cc0fb62306c6f75: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__hc4aa24e1f53551c8: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb99bc681e1e9bc54: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
