import { Gamepad2, ArrowLeft, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function SandboxEmbed() {
    return (
        <div className="w-full max-w-6xl space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-500">

            <div className="flex items-center justify-between border-b border-white/10 pb-4">
                <div>
                    <h1 className="text-3xl font-bold text-white mb-2">The Sovereign Sandbox</h1>
                    <p className="text-violet-300">Play the embedded Bevy game engine example generated by AI.</p>
                </div>
            </div>

            {/* The iframe container holding the isolated game canvas */}
            <div className="glass-panel w-full aspect-[16/9] rounded-2xl overflow-hidden relative shadow-[0_0_30px_rgba(99,102,241,0.2)] bg-black/40">
                <iframe
                    src="/sandbox/game.html"
                    title="Bevy WASM Game"
                    className="w-full h-full border-0 absolute inset-0"
                    allowFullScreen
                ></iframe>
            </div>

            <div className="flex justify-between pt-4">
                <Link to="/module-3" className="glass-button text-slate-400 hover:text-white">
                    <ArrowLeft size={20} /> Back to Module 3
                </Link>
                <Link to="/knowledge-check" className="glass-button glass-button-primary shadow-[0_0_20px_rgba(139,92,246,0.3)] border-indigo-400/50 bg-indigo-600/80 hover:bg-indigo-500 hover:shadow-[0_0_20px_rgba(99,102,241,0.6)]">
                    Take Knowledge Check <ArrowRight size={20} />
                </Link>
            </div>

        </div>
    );
}
